language: ruby
script: "bundle exec rake test"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.4
  - 2.5
  - 2.7
env:
  - PUPPET_GEM_VERSION=2.7.14
  - PUPPET_GEM_VERSION=3.8.5
  - PUPPET_GEM_VERSION=4.8.2
  - PUPPET_GEM_VERSION=5.5.21
  - PUPPET_GEM_VERSION=6.18.0
matrix:
  fast_finish: true
notifications:
  email: false
matrix:
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION=4.8.2
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION=5.5.21
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION=6.18.0
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION=2.7.14
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION=5.5.21
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION=6.18.0
    - rvm: 2.1
      env: PUPPET_GEM_VERSION=2.7.14
    - rvm: 2.1
      env: PUPPET_GEM_VERSION=5.5.21
    - rvm: 2.1
      env: PUPPET_GEM_VERSION=6.18.0
    - rvm: 2.4
      env: PUPPET_GEM_VERSION=2.7.14
    - rvm: 2.4
      env: PUPPET_GEM_VERSION=3.8.5
    - rvm: 2.4
      env: PUPPET_GEM_VERSION=6.18.0
    - rvm: 2.5
      env: PUPPET_GEM_VERSION=2.7.14
    - rvm: 2.5
      env: PUPPET_GEM_VERSION=3.8.5
    - rvm: 2.5
      env: PUPPET_GEM_VERSION=4.8.2
    - rvm: 2.7
      env: PUPPET_GEM_VERSION=2.7.14
    - rvm: 2.7
      env: PUPPET_GEM_VERSION=3.8.5
    - rvm: 2.7
      env: PUPPET_GEM_VERSION=4.8.2
