---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.4
env:
  global:
    - CHECK=parallel_spec BEAKER_PUPPET_COLLECTION=puppet5
  matrix:
    - PUPPET_GEM_VERSION=2.7.14
    - PUPPET_GEM_VERSION=3.8.5
    - PUPPET_GEM_VERSION=4.8.2
    - PUPPET_GEM_VERSION=5.3.3
matrix:
  fast_finish: true
  include:
    -
      env: CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
      rvm: 2.4.4
  exclude:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION=4.8.2
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION=5.3.3
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION=4.8.2
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION=5.3.3
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION=2.7.14
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION=5.3.3
    - rvm: 2.1
      env: PUPPET_GEM_VERSION=2.7.14
    - rvm: 2.1
      env: PUPPET_GEM_VERSION=5.3.3
    - rvm: 2.4
      env: PUPPET_GEM_VERSION=2.7.14
    - rvm: 2.4
      env: PUPPET_GEM_VERSION=3.8.5
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"